# Generated by Django 5.0.9 on 2024-11-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0012_job_object_type_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLogSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "changelog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="human_summary",
                        to="core.objectchange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Changelog Summary",
                "verbose_name_plural": "Changelog Summaries",
            },
        ),
    ]
