# Generated by Django 5.0.9 on 2024-11-04 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_job_object_type_optional"),
        ("netbox_changelog_diff_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelogsummary",
            name="changelog",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_summary",
                to="core.objectchange",
            ),
        ),
    ]
